// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsCPdgtFlpWnra7GNlnpC_8YVY2OF179Q',
    appId: '1:877967297827:web:02d8985c77d6bf069dd096',
    messagingSenderId: '877967297827',
    projectId: 'gamifikasi-19505',
    authDomain: 'gamifikasi-19505.firebaseapp.com',
    storageBucket: 'gamifikasi-19505.firebasestorage.app',
    measurementId: 'G-DEZ0ZVYCZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_An7jdbMsa1naVuYBVyGa1vKIJdNug4',
    appId: '1:877967297827:android:e46bdb98924cf55a9dd096',
    messagingSenderId: '877967297827',
    projectId: 'gamifikasi-19505',
    storageBucket: 'gamifikasi-19505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_ZGUH7-m67syrLUGNDMnbSzb5uQ3SVs',
    appId: '1:877967297827:ios:aaa4e0d55637a6c59dd096',
    messagingSenderId: '877967297827',
    projectId: 'gamifikasi-19505',
    storageBucket: 'gamifikasi-19505.firebasestorage.app',
    iosBundleId: 'com.example.gamifikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_ZGUH7-m67syrLUGNDMnbSzb5uQ3SVs',
    appId: '1:877967297827:ios:aaa4e0d55637a6c59dd096',
    messagingSenderId: '877967297827',
    projectId: 'gamifikasi-19505',
    storageBucket: 'gamifikasi-19505.firebasestorage.app',
    iosBundleId: 'com.example.gamifikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsCPdgtFlpWnra7GNlnpC_8YVY2OF179Q',
    appId: '1:877967297827:web:5f59a48ff08a79019dd096',
    messagingSenderId: '877967297827',
    projectId: 'gamifikasi-19505',
    authDomain: 'gamifikasi-19505.firebaseapp.com',
    storageBucket: 'gamifikasi-19505.firebasestorage.app',
    measurementId: 'G-PVBR8WC38V',
  );
}
